/*
 * Main.java
 *
 * Created on July 28, 2004, 5:09 AM
 */

import dANN.Brain;
import dANN.DNA;

/**
 *
 * @author  freemo
 */
public class Main extends javax.swing.JFrame 
{
    Brain MyBrain;
    DNA MyDNA = new DNA();
    
    /** Creates new form Main */
    public Main()
    {
        MyBrain = new Brain(MyDNA, 3, 1);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        TestButton = new java.awt.Button();
        TrainButton = new java.awt.Button();
        TrainText = new java.awt.TextField();
        OutText = new java.awt.TextArea();
        TrainProgress = new javax.swing.JProgressBar();

        getContentPane().setLayout(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        TestButton.setLabel("Test");
        TestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TestButtonMouseClicked(evt);
            }
        });

        getContentPane().add(TestButton);
        TestButton.setBounds(50, 270, 40, 24);

        TrainButton.setLabel("Train");
        TrainButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrainButtonMouseClicked(evt);
            }
        });

        getContentPane().add(TrainButton);
        TrainButton.setBounds(190, 270, 44, 24);

        TrainText.setText("1000");
        getContentPane().add(TrainText);
        TrainText.setBounds(240, 270, 110, 20);

        OutText.setEditable(false);
        getContentPane().add(OutText);
        OutText.setBounds(10, 10, 380, 250);

        TrainProgress.setValue(50);
        getContentPane().add(TrainProgress);
        TrainProgress.setBounds(10, 310, 350, 16);

        pack();
    }//GEN-END:initComponents

    private void TrainButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrainButtonMouseClicked
        int TrainCycles = Integer.valueOf(this.TrainText.getText()).intValue();
        this.TrainProgress.setMaximum(TrainCycles);
        for(int Lcv = 0; Lcv < TrainCycles; Lcv++)
        {
            double[] CurInput = {0, 0, 0};
            double[] CurTrain = {-1};
            this.MyBrain.SetCurrentInput(CurInput);
            this.MyBrain.PropogateOutput();
            this.MyBrain.SetCurrentTraining(CurTrain);
            this.MyBrain.BackPropogateTraining();


            CurInput[0] = 0;
            CurInput[1] = 0;
            CurInput[2] = 1;
            CurTrain[0] = 1;
            this.MyBrain.SetCurrentInput(CurInput);
            this.MyBrain.PropogateOutput();
            this.MyBrain.SetCurrentTraining(CurTrain);
            this.MyBrain.BackPropogateTraining();        

            CurInput[0] = 0;
            CurInput[1] = 1;
            CurInput[2] = 0;
            CurTrain[0] = 1;
            this.MyBrain.SetCurrentInput(CurInput);
            this.MyBrain.PropogateOutput();
            this.MyBrain.SetCurrentTraining(CurTrain);
            this.MyBrain.BackPropogateTraining(); 

            CurInput[0] = 1;
            CurInput[1] = 0;
            CurInput[2] = 0;
            CurTrain[0] = 1;
            this.MyBrain.SetCurrentInput(CurInput);
            this.MyBrain.PropogateOutput();
            this.MyBrain.SetCurrentTraining(CurTrain);
            this.MyBrain.BackPropogateTraining(); 
            
            CurInput[0] = 1;
            CurInput[1] = 1;
            CurInput[2] = 0;
            CurTrain[0] = -1;
            this.MyBrain.SetCurrentInput(CurInput);
            this.MyBrain.PropogateOutput();
            this.MyBrain.SetCurrentTraining(CurTrain);
            this.MyBrain.BackPropogateTraining(); 
            
            CurInput[0] = 1;
            CurInput[1] = 0;
            CurInput[2] = 1;
            CurTrain[0] = -1;
            this.MyBrain.SetCurrentInput(CurInput);
            this.MyBrain.PropogateOutput();
            this.MyBrain.SetCurrentTraining(CurTrain);
            this.MyBrain.BackPropogateTraining(); 
            
            CurInput[0] = 0;
            CurInput[1] = 1;
            CurInput[2] = 1;
            CurTrain[0] = -1;
            this.MyBrain.SetCurrentInput(CurInput);
            this.MyBrain.PropogateOutput();
            this.MyBrain.SetCurrentTraining(CurTrain);
            this.MyBrain.BackPropogateTraining(); 
            
            CurInput[0] = 1;
            CurInput[1] = 1;
            CurInput[2] = 1;
            CurTrain[0] = -1;
            this.MyBrain.SetCurrentInput(CurInput);
            this.MyBrain.PropogateOutput();
            this.MyBrain.SetCurrentTraining(CurTrain);
            this.MyBrain.BackPropogateTraining();  
            
            this.TrainProgress.setValue(Lcv);
        }
        this.OutText.setText(this.OutText.getText() + "Finished training\r\n");
    }//GEN-LAST:event_TrainButtonMouseClicked

    private void TestButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestButtonMouseClicked
        double[] CurInput = {0, 0, 0};
        this.MyBrain.SetCurrentInput(CurInput);
        this.MyBrain.PropogateOutput();
        double[] CurOutput = {0};
        CurOutput = this.MyBrain.GetCurrentOutput();
        this.OutText.setText(this.OutText.getText() + "0, 0, 0:   " + CurOutput[0] + "\r\n");
        
        CurInput[0] = 1;
        CurInput[1] = 0;
        CurInput[2] = 0;
        this.MyBrain.SetCurrentInput(CurInput);
        this.MyBrain.PropogateOutput();
        CurOutput = this.MyBrain.GetCurrentOutput();
        this.OutText.setText(this.OutText.getText() + "1, 0, 0:   " + CurOutput[0] + "\r\n");
        
        CurInput[0] = 0;
        CurInput[1] = 1;
        CurInput[2] = 0;
        this.MyBrain.SetCurrentInput(CurInput);
        this.MyBrain.PropogateOutput();
        CurOutput = this.MyBrain.GetCurrentOutput();
        this.OutText.setText(this.OutText.getText() + "0, 1, 0:   " + CurOutput[0] + "\r\n");
        
        CurInput[0] = 0;
        CurInput[1] = 0;
        CurInput[2] = 1;
        this.MyBrain.SetCurrentInput(CurInput);
        this.MyBrain.PropogateOutput();
        CurOutput = this.MyBrain.GetCurrentOutput();
        this.OutText.setText(this.OutText.getText() + "0, 0, 1:   " + CurOutput[0] + "\r\n");
        
        CurInput[0] = 1;
        CurInput[1] = 1;
        CurInput[2] = 0;
        this.MyBrain.SetCurrentInput(CurInput);
        this.MyBrain.PropogateOutput();
        CurOutput = this.MyBrain.GetCurrentOutput();
        this.OutText.setText(this.OutText.getText() + "1, 1, 0:   " + CurOutput[0] + "\r\n");
        
        CurInput[0] = 1;
        CurInput[1] = 0;
        CurInput[2] = 1;
        this.MyBrain.SetCurrentInput(CurInput);
        this.MyBrain.PropogateOutput();
        CurOutput = this.MyBrain.GetCurrentOutput();
        this.OutText.setText(this.OutText.getText() + "1, 0, 1:   " + CurOutput[0] + "\r\n");
        
        CurInput[0] = 0;
        CurInput[1] = 1;
        CurInput[2] = 1;
        this.MyBrain.SetCurrentInput(CurInput);
        this.MyBrain.PropogateOutput();
        CurOutput = this.MyBrain.GetCurrentOutput();
        this.OutText.setText(this.OutText.getText() + "0, 1, 1:   " + CurOutput[0] + "\r\n");
        
        CurInput[0] = 1;
        CurInput[1] = 1;
        CurInput[2] = 1;
        this.MyBrain.SetCurrentInput(CurInput);
        this.MyBrain.PropogateOutput();
        CurOutput = this.MyBrain.GetCurrentOutput();
        this.OutText.setText(this.OutText.getText() + "1, 1, 1:   " + CurOutput[0] + "\r\n");
                
    }//GEN-LAST:event_TestButtonMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.OutText.setText("XOR Test\r\n");
        this.setSize(400, 400); 
        
        MyBrain.AddLayerAfterInput(10);
        MyBrain.AddLayerAfterInput(10);
        MyBrain.ConnectAllFeedForward();
    }//GEN-LAST:event_formWindowActivated
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Main().show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea OutText;
    private java.awt.Button TestButton;
    private java.awt.Button TrainButton;
    private javax.swing.JProgressBar TrainProgress;
    private java.awt.TextField TrainText;
    // End of variables declaration//GEN-END:variables
    
}
